/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProjectId = IDL.Text;
export const Platform = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StepName = IDL.Text;
export const Project = IDL.Record({
  'id' : ProjectId,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'platform' : Platform,
  'videoFile' : IDL.Opt(ExternalBlob),
  'stepFiles' : IDL.Vec(IDL.Tuple(StepName, IDL.Opt(ExternalBlob))),
  'steps' : IDL.Vec(IDL.Tuple(StepName, IDL.Text)),
  'currentStep' : StepName,
  'screenRatio' : IDL.Text,
  'niche' : IDL.Text,
});
export const SocialAccount = IDL.Record({
  'id' : IDL.Text,
  'platform' : Platform,
  'accountName' : IDL.Text,
  'connected' : IDL.Bool,
  'handle' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProject' : IDL.Func([Project], [], []),
  'createSocialAccount' : IDL.Func([SocialAccount], [], []),
  'deleteProject' : IDL.Func([ProjectId], [], []),
  'deleteSocialAccount' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProject' : IDL.Func([ProjectId], [Project], ['query']),
  'getSocialAccount' : IDL.Func([IDL.Text], [SocialAccount], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'listSocialAccounts' : IDL.Func([], [IDL.Vec(SocialAccount)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProject' : IDL.Func([Project], [], []),
  'updateSocialAccount' : IDL.Func([SocialAccount], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProjectId = IDL.Text;
  const Platform = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StepName = IDL.Text;
  const Project = IDL.Record({
    'id' : ProjectId,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'platform' : Platform,
    'videoFile' : IDL.Opt(ExternalBlob),
    'stepFiles' : IDL.Vec(IDL.Tuple(StepName, IDL.Opt(ExternalBlob))),
    'steps' : IDL.Vec(IDL.Tuple(StepName, IDL.Text)),
    'currentStep' : StepName,
    'screenRatio' : IDL.Text,
    'niche' : IDL.Text,
  });
  const SocialAccount = IDL.Record({
    'id' : IDL.Text,
    'platform' : Platform,
    'accountName' : IDL.Text,
    'connected' : IDL.Bool,
    'handle' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProject' : IDL.Func([Project], [], []),
    'createSocialAccount' : IDL.Func([SocialAccount], [], []),
    'deleteProject' : IDL.Func([ProjectId], [], []),
    'deleteSocialAccount' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProject' : IDL.Func([ProjectId], [Project], ['query']),
    'getSocialAccount' : IDL.Func([IDL.Text], [SocialAccount], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'listSocialAccounts' : IDL.Func([], [IDL.Vec(SocialAccount)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProject' : IDL.Func([Project], [], []),
    'updateSocialAccount' : IDL.Func([SocialAccount], [], []),
  });
};

export const init = ({ IDL }) => { return []; };